export const vars = {
  "menu_bg": "#F8F8F8",
  "component_background": "#caecff",
  "message_border": "#1ca7c7",
  "main_gradient": "linear-gradient(to right, #56ccf2, #2f80ed)",
  "font_size_base": "14px",
  "text_color": "rgba(0, 0, 0, 0.65)",
  "text_color_secondary": "rgba(0, 0, 0, 0.45)",
  "box_shadow_base": "0 2px 8px rgba(0, 0, 0, 0.15)",
  "primary_color": "#1890ff",
  "link_color": "#1890ff",
  "success_color": "#00B16A",
  "warning_color": "#faad14",
  "error_color": "#F03434",
  "secondary_background_color": "#222",
  "aviasales_bg": "#F3F7FA",
  "aviasales_primary_color": "#2196F3",
  "aviasales_text_color": "#4A4A4A",
  "aviasales_info_color": "#A0B0B9",
  "aviasales_border_color": "#DFE5EC",
  "aviasales_container_color": "#FFFFFF",
  "aviasales_box_shadow": "rgba(0, 0, 0, 0.1)",
  "aviasales_hover_color": "#F1FCFF",
  "aviasales_active_btn_text_color": "#FFFFFF"
}